Add diff to bin/bench{,-tar}, delete output by default.

diff --git a/bin/bench b/bin/bench
--- a/bin/bench
+++ b/bin/bench
@@ -3,10 +3,13 @@ set -eu -o pipefail
 
 readonly repo_dir="$( cd $(dirname ${(%):-%x})/..; pwd )"
 
-IN_PATH="${HOME}/Code/FreeCAD"
+: ${IN_PATH:="${HOME}/Code/FreeCAD"}
 OUT_DIR="${HOME}/tmp/ptar-bench-out/$(date -Is)"
 EXTRACT_DIR="${OUT_DIR}/extract"
-: ${THREADS:=4}
+: ${THREADS:=2}
+: ${RUST_LOG:=ptar=debug}
+: ${DELETE_OUTPUT:=true}
+export RUST_LOG
 
 (
     # build in repo root to pick up rust-toolchain file and .cargo/config.toml file.
@@ -16,9 +19,11 @@ EXTRACT_DIR="${OUT_DIR}/extract"
 
 "${repo_dir}/bin/drop-caches"
 
+echo -e "\nOUT_DIR=${OUT_DIR}"
+
 mkdir -p "${EXTRACT_DIR}"
 
-echo "Starting archiving with ptar"
+echo -e "\nStarting archiving with ptar"
 
 time target/release/ptar \
          --in-path "${IN_PATH}" \
@@ -29,7 +34,7 @@ echo "Finished archiving with ptar"
 
 "${repo_dir}/bin/drop-caches"
 
-echo "Starting extracting"
+echo -e "\nStarting extracting"
 
 time ls ${OUT_DIR}/*.tar.zstd \
      | xargs -I% -P${THREADS} \
@@ -37,4 +42,16 @@ time ls ${OUT_DIR}/*.tar.zstd \
 
 echo "Finished extracting"
 
-echo -e "\nOUT_DIR=${OUT_DIR}"
+echo -e "\nStarting diff"
+
+# `|| true` to continue if there are differences, in particular we need to clean up.
+diff -r "${IN_PATH}" "${EXTRACT_DIR}" || true
+
+echo -e "Finished diff\n"
+
+if [ "${DELETE_OUTPUT}" = "true" ]; then
+    echo "Deleting OUT_DIR=${OUT_DIR}"
+    rm -rf "${OUT_DIR}"
+else
+    echo "Leaving output at OUT_DIR=${OUT_DIR}"
+fi
